id = "jinja2-html"
name = "Jinja2 HTML"
version = "0.1.0"
schema_version = 1
authors = ["Zain Khan <program01code@gmail.com>"]
description = "Language server support for Jinja2 HTML templates with auto-completion, syntax highlighting, and Emmet snippets"
repository = "https://github.com/codeCrack-01/zed-jinja2-html"

[language_servers.jinja2_html_lsp]
name = "Jinja2 HTML LSP"

[language_servers.jinja2_html_lsp.binary]
command = "python"
args = ["-m", "main"]
path = "server"

[grammars.jinja2_html]
repository = "https://github.com/dbt-labs/tree-sitter-jinja2"
rev = "main"

[languages.jinja2_html]
name = "Jinja2 HTML"
grammar = "jinja2_html"
path_suffixes = [
    "j2",
    "jinja",
    "jinja2",
    "html.j2",
    "htm.j2",
    "html.jinja",
    "htm.jinja",
    "html.jinja2",
    "htm.jinja2",
    "html",
]
line_comments = ["{#", "#}"]
block_comment = { start = "{#", end = "#}" }
language_servers = ["jinja2_html_lsp"]
auto_indent_using_last_non_empty_line = true
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "'", end = "'", close = true, newline = false },
    { start = "{%", end = "%}", close = true, newline = true },
    { start = "{{", end = "}}", close = true, newline = false },
    { start = "{#", end = "#}", close = true, newline = false },
    { start = "<", end = ">", close = true, newline = false },
]

[languages.jinja2_html.word_characters]
characters = "_-"

[languages.jinja2_html.autoclose]
pairs = [
    { open = "{", close = "}" },
    { open = "[", close = "]" },
    { open = "(", close = ")" },
    { open = "\"", close = "\"" },
    { open = "'", close = "'" },
    { open = "{%", close = "%}" },
    { open = "{{", close = "}}" },
    { open = "{#", close = "#}" },
    { open = "<", close = ">" },
]

[languages.jinja2_html.prettier]
allowed = true
default_options = { tab_width = 2, print_width = 80 }
plugins = ["@prettier/plugin-jinja-template"]