name = "Jinja2 HTML"
grammar = "jinja2-html"
path_suffixes = ["j2", "jinja", "jinja2", "html.j2", "htm.j2", "html.jinja", "htm.jinja", "html.jinja2", "htm.jinja2"]
line_comments = ["{#", "#}"]
block_comment = ["{#", "#}"]
language_servers = ["jinja2-html-lsp"]
auto_indent_using_last_non_empty_line = true
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
  { start = "{%", end = "%}", close = true, newline = true },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "<", end = ">", close = true, newline = false }
]

[word_characters]
characters = "_-"

[autoclose]
pairs = [
  { open = "{", close = "}" },
  { open = "[", close = "]" },
  { open = "(", close = ")" },
  { open = "\"", close = "\"" },
  { open = "'", close = "'" },
  { open = "{%", close = "%}" },
  { open = "{{", close = "}}" },
  { open = "{#", close = "#}" },
  { open = "<", close = ">" }
]

[prettier]
allowed = true
default_options = { tab_width = 2, print_width = 80 }
plugins = ["@prettier/plugin-jinja-template"]

[language_server]
name = "jinja2-html-lsp"

[snippets]
enabled = true